import "./globals.css";
import { Inter, Roboto } from "next/font/google";
import { Nav } from "./Components/Nav";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "News at NetworkTigers",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      
      <body>
        <header>
          <Nav/>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
