import { Poppins } from "@next/font/google";
import Nav from "./Nav";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <header></header>
        <main>{children}</main>
      </body>
    </html>
  );
}
